import { EncryptedTopicConfiguration } from "./hedera/interfaces/EncryptedTopicConfiguration";
import { CreateEncryptedTopicConfiguration } from "./hedera/interfaces/CreateEncryptedTopicConfiguration";
export declare class EncryptedTopic {
    private readonly encryptedTopicConfiguration;
    private readonly client;
    private crypto;
    private readonly TOPIC_DATA_INDEX;
    private readonly TOPIC_ENCRYPTION_ALGORITHM_INDEX;
    private readonly TOPIC_ENCRYPTION_SIZE_INDEX;
    private readonly TOPIC_ENCRYPTED_KEYS_INDEX;
    private readonly privateKey;
    private topicConfigurationMessage;
    private topicMemoObject;
    private topicId?;
    constructor(encryptedTopicConfiguration: EncryptedTopicConfiguration);
    create(createEncryptedTopicConfiguration: CreateEncryptedTopicConfiguration): Promise<string>;
    addParticipant(publicKey: string): Promise<void>;
    submitMessage(message: string): Promise<number>;
    getMessage(sequenceNumber: number): Promise<string>;
    private createMemoObject;
    private createParticipantsTopic;
    private getEncryptedTopicKeysObjectFromTopicConfigurationMessage;
    private getTopicEncryptionAlgorithmFromTopicConfigurationMessage;
    private getTopicEncryptionSizeFromTopicConfigurationMessage;
    private getMemo;
    private getEncryptionKeyAndInitVector;
    private setConfigurationMessage;
    private initializeCrypto;
    private getSubmitKey;
    private getFileContents;
    private getMessageFromTopicInBase64;
}
