import { EncryptedTopicConfiguration } from "./hedera/interfaces/EncryptedTopicConfiguration";
import { CreateEncryptedTopicConfiguration } from "./hedera/interfaces/CreateEncryptedTopicConfiguration";
import { EncryptionAlgorithms } from "./crypto/enums/EncryptionAlgorithms";
import { KeyPair } from "./crypto/interfaces/KeyPair";
import { IHederaStub } from "./hedera/interfaces/IHederaStub";
export declare class EncryptedTopic {
    private readonly encryptedTopicConfiguration;
    private stub?;
    private readonly hederaStub;
    private readonly privateKey;
    private crypto;
    private topicConfigurationMessage;
    private topicMemoObject;
    private topicId?;
    constructor(encryptedTopicConfiguration: EncryptedTopicConfiguration, stub?: IHederaStub | undefined);
    static generateKeyPair(algorithm: EncryptionAlgorithms): KeyPair;
    create(createEncryptedTopicConfiguration: CreateEncryptedTopicConfiguration): Promise<string>;
    addParticipant(publicKey: string, forwardSecrecy?: boolean): Promise<boolean>;
    submitMessage(message: string): Promise<number>;
    getMessage(sequenceNumber: number): Promise<string>;
    getParticipants(): Promise<string[]>;
    rotateEncryptionKey(): Promise<void>;
    private createTopicMessage;
    private createTopicConfigurationMessage;
    private createMemoObject;
    private getCurrentTopicConfigurationMessageVersion;
    private createParticipantsTopic;
    private getEncryptionAlgorithmFromConfigurationMessage;
    private getEncryptionSizeFromConfigurationMessage;
    private setMemo;
    private getEncryptionKeyAndInitVector;
    private setConfigurationMessage;
    private initializeCrypto;
    private getTopicData;
    private getSubmitKey;
    private getEncryptedTopicKeysObjectFromTopicConfigurationMessage;
    private getMessageFromTopic;
}
