name: pull-request

on:
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  build-unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

      - name: Unit test
        run: npm run test:unit
